const TIMER_ACTION = {
  INCREASE_TIMER: "INCREASE_TIMER",
  START_TIMER: "START_TIMER",
  RESET_TIMER: "RESET_TIMER",
  STOP_TIMER: "STOP_TIMER",
  PENALTY_TIMER: "PENALTY_TIMER",
  INITIAL: "INITIAL",
};

export { TIMER_ACTION };
